/*
 * This source file was generated by the Gradle 'init' task
 */
package oop.java.dom1of1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void testApp() {
        // Test the App class
        App.main(new String[] {});
    }

    @Test
    void testVehicle() {
        // Test the Vehicle class
        Vehicle vehicle = new Car("C001", "Toyota Corolla", 50.0);
        assertEquals("C001", vehicle.getVehicleId());
        assertEquals("Toyota Corolla", vehicle.getModel());
        assertEquals(50.0, vehicle.getBaseRentalRate());
        assertTrue(vehicle.isAvailable());
        vehicle.setAvailable(false);
        assertFalse(vehicle.isAvailable());
        vehicle.setAvailable(true);
        assertTrue(vehicle.isAvailable());
    }

    @Test
    void testCar() {
        // Test the Car class
        Car car = new Car("C001", "Toyota Corolla", 50.0);
        assertEquals(50.0, car.calculateRentalCost(3));
        assertTrue(car.isAvailableForRental());
        car.rent(new Customer("Alice"), 3);
        assertFalse(car.isAvailableForRental());
        car.returnVehicle();
        assertTrue(car.isAvailableForRental());
    }

    @Test
    void testMotorcycle() {
        // Test the Motorcycle class
        Motorcycle motorcycle = new Motorcycle("M001", "Honda CB400", 30.0);
        assertEquals(90.0, motorcycle.calculateRentalCost(3));
        assertTrue(motorcycle.isAvailableForRental());
        motorcycle.rent(new Customer("Bob"), 3);
        assertFalse(motorcycle.isAvailableForRental());
        motorcycle.returnVehicle();
        assertTrue(motorcycle.isAvailableForRental());
    }

    @Test
    void testTruck() {
        // Test the Truck class
        Truck truck = new Truck("T001", "Isuzu NQR", 100.0);
        assertEquals(300.0, truck.calculateRentalCost(3));
        assertTrue(truck.isAvailableForRental());
        truck.rent(new Customer("Charlie"), 3);
        assertFalse(truck.isAvailableForRental());
        truck.returnVehicle();
        assertTrue(truck.isAvailableForRental());
    }
}
